# Generated by Django 4.2.3 on 2023-08-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='author',
        ),
    ]
